#!/usr/bin/env python
"""Run deckmaster from the current dir."""
import os
import argparse

try:
	import app as deckmaster
except ImportError:
	import deckmaster

brk = """
********************************************************************************
"""

debug_log_stmt = "RUNNING IN DEBUG MODE"
working_directory_stmt = "WORKING IN DIRECTORY %s"

if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        description='Serve bower packages and local assets.',
    )
    parser.add_argument('--no-debug','-N',
        dest='debug',
        action='store_false',
        help="don't show debugger on exception or reload on file update",
    )
    parser.add_argument('--workdir','-w',
        dest='workdir',
        nargs='?',
        type=str,
        help='specify a working directory other than current directory',
        default=None
    )
    parser.add_argument('--port','-p',
        dest='port',
        nargs='?',
        type=int,
        help='port to serve from',
        default=None
    )

    args = parser.parse_args()

    try:
        workdir = os.path.abspath(args.workdir)
    except AttributeError:
        workdir = None

    if workdir is not None:
        os.chdir(workdir)
        print working_directory_stmt % workdir

    app = deckmaster.get_instance()
    app.config['DEBUG'] = args.debug
    if args.debug:
        print brk
        print debug_log_stmt
    try:
        app.config['WORKDIR'] = os.path.abspath(args.workdir)
    except AttributeError:
        app.config['WORKDIR'] = None
    
    print '\n'
    app.run(port=args.port)
