#!/usr/bin/env python
"""Run deckmaster from the local dir."""
import os

try:
	from app import app
except ImportError:
	from deckmaster import app
	app = app.app

if __name__ == "__main__":
    app.config['DEBUG'] = True
    app.run()
